### PR TITLE
Bump to 1.18.1

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@tschoonj, if you know what you are doing with gst-python (i.e. I don't, I just needed this packaged for something else) please add yourself as a maintainer of the conda recipe.

**Comment by tschoonj** [comment]
Hi @duncanmmacleod  I will once I get this PR sorted out...

**Comment by tschoonj** [comment]
@duncanmmacleod I believe that this PR is now ready for a merge.

**Comment by duncanmmacleod** [comment]
I'm a little confused about the large gap from 1.14.x to 1.18.x, mainly in how that will affect conda-forge pinnings of the upstream gstreamer package, but otherwise I'm happy. As I mentioned before, I am gstreamer-naive, so if this works for you, it probably works for everyone else.

**Pull request merged**
